# Change these first
owner: mikemahoney218 # Your GitHub organization or username, where this repository lives
repo: uptime_proof # The name of this repository

sites:
  - name: iv
    url: https://waterservices.usgs.gov/nwis/iv/?format=json&sites=01103025
  - name: dv
    url: https://waterservices.usgs.gov/nwis/dv/?format=json&sites=01103025
  - name: site
    url: https://waterservices.usgs.gov/nwis/site/?format=rdb&sites=01103025
  - name: stats
    url: https://waterservices.usgs.gov/nwis/stat/?format=rdb&sites=01103025&statReportType=daily&statTypeCd=all
  - name: gwlevels
    url: https://waterservices.usgs.gov/nwis/gwlevels/?format=json&sites=422819071065701

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime_proof
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WaterServices Status
  introTitle: "Unofficial page tracking WaterServices availability."
  introMessage: This is a an unofficial website tracking the availability of WaterServices APIs. This is a personal project, not affiliated with any organization.
  navbar:
    - title: Status
      href: /uptime_proof
    - title: GitHub
      href: https://github.com/mikemahoney218/uptime_proof

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
